ministryofjustice/hmpps-support-additional-needs-ui

assets/scss/components/_api-error.scss
assets/scss/index.scss
helm_deploy/hmpps-support-additional-needs-ui/values.yaml
server/app.ts
server/config.ts
server/middleware/apiErrorMiddleware.ts
server/middleware/auditMiddleware.test.ts
server/routes/search/index.ts
server/routes/search/searchController.ts
server/utils/result/result.test.ts
server/utils/result/result.ts
server/views/pages/search/_searchResults.njk
server/views/pages/search/index.njk
server/views/partials/layout.njk

PR to to the basic wiring of the SearchService (service layer to an API call to our /search API) into the search page route.
The PR introduces the pattern of the Result class to wrap the promise, and allowing basic logic in the nunjucks template to determine whether the promise was resolved or not
This PR is deliberately just a skeleton. This PR is about introducing the pattern/approach, and making sure we have it right.
Tests, fleshing our the view, etc etc, will come later

RR-1471 - Wire SearchService call into /search route

---

server/@types/dto/index.d.ts
server/@types/supportAdditionalNeedsApi/index.d.ts
server/data/mappers/createEducationSupportPlanRequestMapper.test.ts
server/data/mappers/createEducationSupportPlanRequestMapper.ts
server/data/mappers/educationSupportPlanDtoMapper.test.ts
server/data/mappers/educationSupportPlanDtoMapper.ts
server/testsupport/createEducationSupportPlanRequestTestDataBuilder.ts
server/testsupport/educationSupportPlanDtoTestDataBuilder.ts
server/testsupport/educationSupportPlanResponseTestDataBuilder.ts

This PR is part of the story RR-1588 to add a new screen (Additional Information) to the Create Education Support Plan journey.
The API already supports this extra question (as an optional field in the API request), so this PR re-imports the swagger spec to build the model classes, updates the DTO, and updates the mappers.
The API models this extra field as a field called `detail`. I have added it to the DTO as a field called `additionalInformation` as this is a better reflection of the UI screen (to be added in my next PR); and the mapper handles the mapping between the API naming and DTO naming 👍 
The next PR will add the route, screen etc and start wiring it all up

RR-1588 - Reimport swagger spec, DTO and mappers to get new `detail` field from API request/response objects

---

integration_tests/e2e/education-support-plan/create/checkYourAnswersChangeLinks.cy.ts
integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts
integration_tests/e2e/education-support-plan/create/createEducationSupportPlanPreventOutOfSequenceNavigation.cy.ts
integration_tests/e2e/education-support-plan/create/removeOtherPeopleConsulted.cy.ts
integration_tests/e2e/education-support-plan/refuse-plan/refuseEducationSupportPlan.cy.ts
integration_tests/e2e/profile/overview.cy.ts
integration_tests/e2e/search/search.cy.ts
integration_tests/mockApis/supportAdditionalNeedsApi.ts
server/routes/profile/middleware/retrieveCurrentEducationSupportPlanCreationSchedule.test.ts
server/routes/profile/middleware/retrieveCurrentEducationSupportPlanCreationSchedule.ts
server/routes/profile/overview/index.ts
server/services/educationSupportPlanScheduleService.ts

This PR adds the new middleware that retrieves the prisoner's current ELSP Creation Schedule , and wires it into the Overview page route (because we will need it on the Overview page to determine whether to show the "Refuse Plan" and "Create Plan" action links - not in this PR)
Because I've wired the middleware into the route, I've had to setup the wiremock stub for the cypress tests and wire it into the relevant tests (because otherwise the cypress tests are not doing quite what they should do because they'll be getting a 404 from wiremock when trying to get the prisoner's ESLP Creation Schedule)

RR-1626 - Middleware and basic wiring to get prisoner ELSP creation schedule

---

integration_tests/e2e/profile/overview.cy.ts
integration_tests/mockApis/supportAdditionalNeedsApi.ts
server/@types/viewModels/index.d.ts
server/routes/profile/middleware/retrieveCurrentEducationSupportPlanCreationSchedule.test.ts
server/routes/profile/middleware/retrieveCurrentEducationSupportPlanCreationSchedule.ts
server/routes/profile/overview/overviewController.test.ts
server/routes/profile/overview/overviewController.ts
server/views/components/actions-card/_educationSupportPlanActions.njk
server/views/components/actions-card/_educationSupportPlanActions.test.ts
server/views/components/actions-card/actionCards.test.njk
server/views/components/actions-card/actionsCard.test.ts
server/views/pages/profile/overview/index.njk
server/views/pages/profile/overview/index.test.ts
server/views/pages/search/index.njk

This PR ties up the work for the Refuse Plan epic (and Create Plan epic), in that it uses the previously retrieved ELSP Plan Creation Schedule to determine whether to show the links to Create and Refuse the plan in the Actions menu (ie. only show these 2 links if the status is SCHEDULED)

RR-1626 - Render Support Plan Actions only when the schedule status is scheduled

---

server/@types/dto/index.d.ts
server/@types/express/index.d.ts
server/routes/strengths/create/index.ts
server/routes/strengths/create/middleware/checkStrengthDtoExistsInJourneyData.test.ts
server/routes/strengths/create/middleware/checkStrengthDtoExistsInJourneyData.ts
server/routes/strengths/create/middleware/createEmptyStrengthDtoIfNotInJourneyData.test.ts
server/routes/strengths/create/middleware/createEmptyStrengthDtoIfNotInJourneyData.ts
server/testsupport/strengthDtoTestDataBuilder.ts

PR to create the StrengthDto , which we'll use to carry the data from page to page in the Create Strength journey
And also to create the 2 middlewares we need for the Create Strength journey (the first is to create an empty StrengthDto in the journeyData at the beginning of the journey; the 2nd is to check it has been created and exists in the journeyData on each subsequent page in the journey)

RR-1684 - Define the StrengthDto and journey middleware functions

---

integration_tests/e2e/additional-learning-needs-screener/create/recordAlnScreenerPreventOutOfSequenceNavigation.cy.ts
server/@types/dto/index.d.ts
server/@types/express/index.d.ts
server/routes/additional-learning-needs-screener/create/index.ts
server/routes/additional-learning-needs-screener/create/middleware/checkAlnScreenerDtoExistsInJourneyData.test.ts
server/routes/additional-learning-needs-screener/create/middleware/checkAlnScreenerDtoExistsInJourneyData.ts
server/routes/additional-learning-needs-screener/create/middleware/createEmptyAlnScreenerDtoIfNotInJourneyData.test.ts
server/routes/additional-learning-needs-screener/create/middleware/createEmptyAlnScreenerDtoIfNotInJourneyData.ts
server/testsupport/alnScreenerDtoTestDataBuilder.ts

PR to add the initial `AlnScreenerDto` (will be fleshed out with additional fields as we progress through the stories), and the 2 middlewares to:
* create the DTO in the journeyData if it doesn't exist at the start of the journey
* check the DTO exists in the journeyData on each screen of the journey
Also added the cypress test to check the user cannot navigate to the ALN Screener journey pages out of sequence (these essentially test the middleware that checks the DTO exists in the journeyData)

RR-1700 - Initial DTO & middlewares

---

assets/scss/components/_additional-learning-needs-form.scss
assets/scss/index.scss
server/routes/additional-learning-needs-screener/create/add-challenges/addChallengesController.ts
server/routes/additional-learning-needs-screener/create/index.ts
server/views/pages/additional-learning-needs-screener/add-challenges/index.njk

Basic controller and view for the "Add challenges" screen.
The route calls the reference data middleware in order to get the challenges grouped by challenge category; and then the view loops through the challenge categories and challenges in order to dynamically layout the form.
At the moment the screen labels are the underlying challenge type codes; this will be addressed in my next PR

RR-1699 - Basic controller and view

---

server/@types/supportAdditionalNeedsApiClient/index.d.ts
server/data/mappers/alnScreenerRequestMapper.test.ts
server/data/mappers/alnScreenerRequestMapper.ts
server/data/supportAdditionalNeedsApiClient.test.ts
server/data/supportAdditionalNeedsApiClient.ts
server/services/additionalLearningNeedsScreenerService.test.ts
server/services/additionalLearningNeedsScreenerService.ts
server/services/challengeService.test.ts
server/services/conditionService.test.ts
server/services/index.ts
server/services/strengthService.test.ts
server/testsupport/alnScreenerRequestTestDataBuilder.ts

PR to add the client and service methods to be able to call the API to record an ALN Screener
(service not wired into anything yet; that will be in my next PR)

RR-1702 - Add client and service methods to record ALN Screener

---

server/routes/additional-learning-needs-screener/create/add-challenges/addChallengesController.test.ts
server/routes/additional-learning-needs-screener/create/add-challenges/addChallengesController.ts
server/routes/additional-learning-needs-screener/create/add-strengths/addStrengthsController.test.ts
server/routes/additional-learning-needs-screener/create/add-strengths/addStrengthsController.ts

Small PR to fix a small bug on the "add challenges" and "add strengths" form handling.
Both these pages contain a list of checkboxes, where you need to select at least 1. The form submission submits the selected checkboxes as an array, and then the zod validator checks you have selected at least 1 (and that you've not selected one or more of the options AND "None")
Anyway, in the case where you don't select any checkboxes at all and submit the form, the validator correctly fails the validation and redirects you back to the same page. In the GET handler for the page, we populate the form object (that the view uses) with `invalidForm` (populated by the zod validator with the original request body/fields). But in the case of no checkboxes selected, `invalidForm` has a `challengeTypeCodes` …

RR-1669 - Fix "add challenges" and "add strengths" form mapping

---

integration_tests/e2e/conditions/create/createConditions.cy.ts
server/views/components/actions-card/_challengesActions.test.ts
server/views/components/actions-card/_conditionsActions.test.ts
server/views/components/actions-card/_educationSupportPlanActions.test.ts
server/views/components/actions-card/_strengthsActions.test.ts
server/views/pages/conditions/select-conditions/index.njk
server/views/pages/conditions/select-conditions/index.test.ts

This PR introduces the logic to have a slightly different heading on the "Select conditions" screen, based on whether the user has permission to create only self-declared conditions, or self-declared and diagnosed conditions:
* If the user is a “default access” user (and therefore only has permission to record self-declared conditions), the heading is `What self-declared condition do you want to record for <prisoner name>?`
* If the user has permissions to record diagnosed conditions, the heading is `What self-declared or diagnosed condition do you want to record for <prisoner name>?`
Functionally there are no changes to the screen or journey; it is simply some logic re: the heading (the next story RR-1706 will make some functional changes to the Details screen, but this story and PR is …

RR-1705 - Logic to display relevant header for self-declared/diagnosed conditions

---

integration_tests/e2e/conditions/create/createConditions.cy.ts
server/routes/conditions/validationSchemas/detailsSchema.test.ts
server/routes/conditions/validationSchemas/detailsSchema.ts

RR-1706 is to add the additional radio button fields to the Conditions Details form to collect whether the Condition is self-declared or diagnosed:
These radio button fields are only to be asked if the user has the permission to record Diagnosed Conditions; but its all part of the same "Add Conditions" journey.
What this essentially means is that:
* The radio buttons are conditionally displayed
* In respect of the form submission, the form fields for the radio buttons may or may not be there
* In respect of form validation, the form fields may or may not be there, but if they are there then then are mandatory for the set of ConditionTypes already collected
* The mapping of the form data -> DTO -> API request object will need to cater for these conditional questions
* The cypress tests …

RR-1706 - Validator changes to optionally validate conditionDiagnosis form fields

---

server/routes/conditions/create/details/detailsController.test.ts
server/routes/conditions/create/details/detailsController.ts
server/views/pages/conditions/details/index.njk
server/views/pages/conditions/details/index.test.ts

RR-1706 is to add the additional radio button fields to the Conditions Details form to collect whether the Condition is self-declared or diagnosed:
These radio button fields are only to be asked if the user has the permission to record Diagnosed Conditions; but its all part of the same "Add Conditions" journey.
What this essentially means is that:
* The radio buttons are conditionally displayed
* In respect of the form submission, the form fields for the radio buttons may or may not be there
* In respect of form validation, the form fields may or may not be there, but if they are there then then are mandatory for the set of ConditionTypes already collected
* The mapping of the form data -> DTO -> API request object will need to cater for these conditional questions
* The cypress tests …

RR-1706 - Add conditional radio buttons, asking if the condition is self-declared or diagnosed

---

server/@types/dto/index.d.ts
server/data/mappers/challengeDtoMapper.ts
server/data/mappers/conditionDtoMapper.test.ts
server/data/mappers/conditionDtoMapper.ts
server/data/mappers/referencedAndAuditableMapper.ts
server/data/supportAdditionalNeedsApiClient.test.ts
server/data/supportAdditionalNeedsApiClient.ts
server/services/conditionService.test.ts
server/services/conditionService.ts
server/testsupport/auditFieldsTestDataBuilder.ts
server/testsupport/challengeResponseTestDataBuilder.ts
server/testsupport/conditionResponseTestDataBuilder.ts
server/testsupport/educationSupportPlanResponseTestDataBuilder.ts
server/testsupport/planCreationScheduleResponseTestDataBuilder.ts
server/testsupport/strengthResponseTestDataBuilder.ts

PR to add the API client and service methods to be able to retrieve a prisoners conditions from the API
Also includes some refactoring of the challenge mapper, and some test data builders, to reduce duplication re: common audit & reference number fields

RR-1711 - Client and service methods to get conditions

---

integration_tests/e2e/profile/conditions.cy.ts
integration_tests/pages/profile/conditionsPage.ts
server/testsupport/auditFieldsTestDataBuilder.ts
server/testsupport/challengeResponseTestDataBuilder.ts
server/testsupport/conditionDtoTestDataBuilder.ts
server/testsupport/conditionResponseTestDataBuilder.ts
server/testsupport/educationSupportPlanResponseTestDataBuilder.ts
server/testsupport/planCreationScheduleResponseTestDataBuilder.ts
server/testsupport/strengthResponseTestDataBuilder.ts
server/views/pages/profile/conditions/components/conditions-summary-card/conditionsSummaryCard.test.njk
server/views/pages/profile/conditions/components/conditions-summary-card/conditionsSummaryCard.test.ts
server/views/pages/profile/conditions/components/conditions-summary-card/macro.njk
server/views/pages/profile/conditions/components/conditions-summary-card/template.njk
server/views/pages/profile/conditions/index.njk
server/views/pages/profile/conditions/index.test.ts

PR to render both Diagnosed and Self-declared conditions on the Conditions profile page.
(The only bit that is missing is the lookup from prison ID to prison name - that will come next)

RR-1711 - Render conditions in view - diagnosed + self declared conditions

---

server/@types/dto/index.d.ts
server/data/mappers/alnScreenerResponseDtoMapper.test.ts
server/data/mappers/alnScreenerResponseDtoMapper.ts
server/data/mappers/challengeDtoMapper.test.ts
server/data/mappers/challengeDtoMapper.ts
server/routes/profile/challenges/challengesController.test.ts
server/routes/profile/challenges/challengesController.ts
server/routes/profile/challenges/index.ts
server/routes/profile/middleware/retrieveCurrentChallenges.test.ts
server/routes/profile/middleware/retrieveCurrentChallenges.ts
server/services/additionalLearningNeedsScreenerService.test.ts
server/services/challengeService.test.ts
server/services/challengeService.ts
server/testsupport/alnScreenerDtoTestDataBuilder.ts
server/testsupport/challengeResponseDtoTestDataBuilder.ts
server/views/pages/profile/challenges/_challenges.njk
server/views/pages/profile/challenges/components/challenges-summary-card/alnChallengesSummaryCard.test.njk
server/views/pages/profile/challenges/components/challenges-summary-card/aln_template.njk
server/views/pages/profile/challenges/components/challenges-summary-card/challengesSummaryCard.test.njk
server/views/pages/profile/challenges/components/challenges-summary-card/challengesSummaryCard.test.ts
server/views/pages/profile/challenges/components/challenges-summary-card/macro.njk
server/views/pages/profile/challenges/components/challenges-summary-card/template.njk
server/views/pages/profile/challenges/index.njk

Apologies for the mega PR.
This PR updates the challenges view to be most of the way there:
Adding the following to the challenges view:
* Displaying manually created challenges
* Displaying ALN created challenges
* Retrieval of ALN challenges from ALN reader endpoint
* Order the challenges as per ticket, categories order alphabetically, challenges within categories ordered - manually created first ordered by recency, ALN created after ordered alphabetically.

RR-1751 and RR-1735 Challenges View

---

assets/scss/components/_actions-card.scss
server/views/pages/profile/components/actions-card/actionCards.test.njk
server/views/pages/profile/components/actions-card/actionsCard.test.ts
server/views/pages/profile/components/actions-card/macro.njk
server/views/pages/profile/components/actions-card/template.njk
server/views/pages/profile/education-support-plan/index.njk

PR that adds the new Actions Bar component for the Profile pages
At the moment the actions bar items are only the ones that all users can access (aka "default access"); and I've only plumbed it into the Education Support Plan tab to make sure it works 👍 
I'll plumb it into the other tabs, and remove the old component, in my next PR

RR-1843 - Action Bar component with initial "default access" actions

---

server/routes/middleware/retrieveChallenges.test.ts
server/routes/middleware/retrieveChallenges.ts
server/routes/profile/challenges/index.ts
server/routes/profile/overview/index.ts

PR to refactor the middleware that retrieve the challenges from within the routes/profile/middleware subdirectory up one level to routes/middleware
This is so that this middleware can be re-used by other routes. At the moment only the profile pages/routes use them, hence where they are currently in the directory structure, but [RR-1791](https://dsdmoj.atlassian.net/browse/RR-1791) calls for challenges to be displayed as part of the Create ELSP journey, hence moving them to a place that is more convenient for both routes to be able to call them from.
Also, a minor rename in the middleware file and exported function - the previous use of the term "Current" in the name was wrong/misleading, and the middleware gets ALL challenges from the service (and subsequent code filters for the "current" …

RR-1791 - Move challenges middleware so that it can be re-used by other routes

---

integration_tests/e2e/profile/overviewSupportStrategies.cy.ts
integration_tests/pages/profile/overviewPage.ts

* Add initial cypress tests for Support strategies on the overview page.
* More detailed tests to be added for the overview page once completed.

RR-1755 Cypress tests for Support Strategies on Overview page

---

server/routes/education-support-plan/validationSchemas/reviewSupportPlanSchema.test.ts
server/routes/education-support-plan/validationSchemas/reviewSupportPlanSchema.ts
server/views/pages/education-support-plan/review-support-plan/index.njk

* Updates review date validation schema to prevent to fail with appropriate message if an October 2025 date is selected.
* Add a temporary workaround for one of the existing validation tests to prevent it from failing when the test is run in Oct.

RR-1872 prevent Oct 2025 review dates

---

helm_deploy/hmpps-support-additional-needs-ui/values.yaml
server/views/pages/support-strategies/detail/index.njk

Set serviceAccount name in helm deploy to get audit working; plus a minor (unrelated) content change

RR-1935 - Set serviceAccount name in helm deploy to get audit working

---

server/app.ts
server/utils/azureAppInsights.ts

This PR updates the middlewares so that app insights logs username and activeCaseloadId
Tested locally by setting the appInsights connection string from `dev` in my local `.env` file:

RR-1890 - Update middlewares so that app insights logs username and activeCaseloadId

---

server/@types/dto/index.d.ts
server/@types/express/index.d.ts
server/data/mappers/educationSupportPlanDtoMapper.test.ts
server/data/mappers/educationSupportPlanDtoMapper.ts
server/routes/education-support-plan/review/index.ts
server/routes/education-support-plan/review/middleware/createEmptyReviewEducationSupportPlanDtoIfNotInJourneyData.test.ts
server/routes/education-support-plan/review/middleware/createEmptyReviewEducationSupportPlanDtoIfNotInJourneyData.ts
server/routes/education-support-plan/review/middleware/retrieveEducationSupportPlan.ts
server/routes/education-support-plan/review/who-reviewed-the-plan/whoReviewedThePlanController.test.ts
server/routes/education-support-plan/review/who-reviewed-the-plan/whoReviewedThePlanController.ts
server/services/educationSupportPlanService.test.ts
server/testsupport/educationSupportPlanDtoTestDataBuilder.ts
server/testsupport/reviewEducationSupportPlanDtoTestDataBuilder.ts

PR that refactors the way the Review journey will store the data from screen to screen.
Originally I thought that the journey was close enough to the Create ELSP journey that we could use the existing `EducationSupportPlanDto` and just add a couple of fields - thats what I did for screen 1 (Who reviewed the plan? screen)
Now I'm about to start on the 2nd screen (who else was consulted? screen) its become clear that there are more differences than I thought, and we'll be adding lots of new fields to the `EducationSupportPlanDto`
This PR refactors this approach. It puts the `EducationSupportPlanDto` and associated mappers etc back to how they were (ie. without the fields for the review journey), and creates a new DTO `ReviewEducationSupportPlanDto` that contains just the additional fields …

RR-1776 - Refactor DTO; introduce DTO specifically for the Review journey

---

integration_tests/e2e/search/search.cy.ts
server/routes/search/index.ts
server/routes/testutils/appSetup.ts

Set default sort order on prisoner list page depending on what the user is allowed to do in the system
If the user is not allowed to see the Plan Statuses and Deadline Dates on the prisoner list search results screen ("default" access), then the default order should be on prisoner name ascending.
If the user is allowed to see the Plan Statuses and Deadline Dates on the prisoner list search results screen (users with editor or manager roles), then the default order should be on deadline date ascending.

RR-1956 - Set default sort order on prisoner list page
