server/@types/supportAdditionalNeedsApiClient/index.d.ts, server/@types/viewModels/index.d.ts, server/data/mappers/prisonerSearchMapper.test.ts, server/data/mappers/prisonerSearchMapper.ts, server/services/searchService.test.ts, server/services/searchService.ts, server/testsupport/prisonerSearchTestDataBuilder.ts, server/views/pages/search/_searchResults.njk, server/views/partials/layout.njk
PR to add pagination controls to the search results screen:
=> RR-1471 - Add pagination

server/data/mappers/prisonerSearchMapper.test.ts, server/data/mappers/prisonerSearchMapper.ts, server/routes/search/index.ts, server/routes/search/searchController.ts, server/services/searchService.ts, server/views/components/sortable-table-header/macro.njk, server/views/components/sortable-table-header/template.njk, server/views/pages/search/_searchBox.njk, server/views/pages/search/_searchResults.njk
PR to add sortable column headers to the search results table
=> RR-1471 - Add sortable column headers

assets/scss/index.scss, assets/scss/overrides/_print.scss, server/filters/formatPrisonerNameFilter.test.ts, server/filters/formatPrisonerNameFilter.ts, server/testsupport/prisonerSummaryTestDataBuilder.ts, server/utils/nunjucksSetup.ts, server/views/pages/search/_searchResults.njk
PR to format the names as per the design, to make each name a link to their Overview page (yet to be developed), and implement a basic print style sheet (cribbed from LWP 😁 )
=> RR-1471 - Format names and link to overview

assets/js/backLink.mjs, assets/js/index.js, assets/scss/overrides/_local.scss, integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/whoCreatedThePlanPage.ts, integration_tests/pages/page.ts, server/enums/planCreatedByValue.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/who-created-the-plan/whoCreatedThePlanController.ts, server/routes/education-support-plan/validationSchemas/whoCompletedThePlanSchema.test.ts, server/routes/education-support-plan/validationSchemas/whoCompletedThePlanSchema.ts, server/views/pages/education-support-plan/layout.njk, server/views/pages/education-support-plan/who-created-the-plan/index.njk, server/views/partials/layout.njk
PR to create the "Who Created The Plan" page inc. validation, routing, and basic cypress test
=> RR-1546 - Who Created The Plan page

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/otherPeopleConsultedPage.ts, integration_tests/pages/education-support-plan/reviewNeedsConditionsStrengthsPage.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedController.test.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedController.ts, server/routes/education-support-plan/create/review-needs-conditions-strengths/reviewNeedsConditionsStrengthsController.test.ts, server/routes/education-support-plan/create/review-needs-conditions-strengths/reviewNeedsConditionsStrengthsController.ts, server/routes/education-support-plan/create/who-created-the-plan/whoCreatedThePlanController.test.ts, server/views/pages/education-support-plan/other-people-consulted/index.njk, server/views/pages/education-support-plan/review-needs-conditions-strengths/index.njk
This PR adds the "Other People Consulted" and "Reviews Needs, Conditions and Strengths" pages to the create ELSP flow (pages 2 and 3 in the journey)
Currently the designs for these 2 pages are undefined, but we do know these pages will be at page 2 and 3 in the flow; and we need these pages to exist in the flow so that we can define the rest of the pages and flow. As such the nunjucks templates/contents for these pages is just some basic placeholder text.
=> RR-1547 - Other People Consulted and Review Needs Conditions and Strengths pages

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/learningEnvironmentAdjustmentsPage.ts, server/enums/yesNoValue.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/learning-environment-adjustments/learningEnvironmentAdjustmentsController.test.ts, server/routes/education-support-plan/create/learning-environment-adjustments/learningEnvironmentAdjustmentsController.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedController.test.ts, server/routes/education-support-plan/create/review-needs-conditions-strengths/reviewNeedsConditionsStrengthsController.test.ts, server/routes/education-support-plan/create/review-needs-conditions-strengths/reviewNeedsConditionsStrengthsController.ts, server/routes/education-support-plan/validationSchemas/learningEnvironmentAdjustmentsSchema.test.ts, server/routes/education-support-plan/validationSchemas/learningEnvironmentAdjustmentsSchema.ts, server/views/pages/education-support-plan/learning-environment-adjustments/index.njk, server/views/partials/layout.njk
PR to add the Learning Environment Adjustments page to the Create ELSP journey (page 4 in the flow)
=> RR-1550 - Learning Environment Adjustments page

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/teachingAdjustmentsPage.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/learning-environment-adjustments/learningEnvironmentAdjustmentsController.ts, server/routes/education-support-plan/create/teaching-adjustments/teachingAdjustmentsController.test.ts, server/routes/education-support-plan/create/teaching-adjustments/teachingAdjustmentsController.ts, server/routes/education-support-plan/validationSchemas/teachingAdjustmentsSchema.test.ts, server/routes/education-support-plan/validationSchemas/teachingAdjustmentsSchema.ts, server/views/pages/education-support-plan/teaching-adjustments/index.njk
PR to add the Teaching Adjustments page to the Create ELSP journey (page 5 in the flow)
=> RR-1549 - Teaching Adjustments page

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/examArrangementsPage.ts, integration_tests/pages/education-support-plan/specificTeachingSkillsPage.ts, server/routes/education-support-plan/create/exam-arrangements/examArrangementsController.test.ts, server/routes/education-support-plan/create/exam-arrangements/examArrangementsController.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/specific-teaching-skills/specificTeachingSkillsController.test.ts, server/routes/education-support-plan/create/specific-teaching-skills/specificTeachingSkillsController.ts, server/routes/education-support-plan/validationSchemas/examArrangementsSchema.test.ts, server/routes/education-support-plan/validationSchemas/examArrangementsSchema.ts, server/routes/education-support-plan/validationSchemas/specificTeachingSkillsSchema.test.ts, server/routes/education-support-plan/validationSchemas/specificTeachingSkillsSchema.ts, server/views/pages/education-support-plan/exam-arrangements/index.njk, server/views/pages/education-support-plan/specific-teaching-skills/index.njk
PR to add the Specific Teaching Skills page (page 6 in the flow), and Exam Arrangements page (page 7 in the flow) to the Create ELSP journey
=> RR-1551 & RR-1552 - Specific Teaching Skills and Exam Arrangements pages

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/reviewSupportPlanPage.ts, server/middleware/validationMiddleware.test.ts, server/middleware/validationMiddleware.ts, server/routes/education-support-plan/create/education-health-care-plan/educationHealthCarePlanController.test.ts, server/routes/education-support-plan/create/exam-arrangements/examArrangementsController.test.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/learning-needs-support-practitioner-support/learningNeedsSupportPractitionerSupportController.test.ts, server/routes/education-support-plan/create/review-support-plan/reviewSupportPlanController.test.ts, server/routes/education-support-plan/create/review-support-plan/reviewSupportPlanController.ts, server/routes/education-support-plan/validationSchemas/reviewSupportPlanSchema.test.ts, server/routes/education-support-plan/validationSchemas/reviewSupportPlanSchema.ts, server/views/pages/education-support-plan/review-support-plan/index.njk, server/views/partials/layout.njk
PR to add the Review Support Plan page (page 10 in the flow) to the Create ELSP journey
=> RR-1555 - Set Review Date page

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/otherPeopleConsultedPage.ts, integration_tests/support/commands.ts, server/@types/dto/index.d.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedController.test.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedController.ts, server/routes/education-support-plan/validationSchemas/wereOthePeopleConsultedSchema.test.ts, server/routes/education-support-plan/validationSchemas/wereOtherPeopleConsultedSchema.ts, server/views/pages/education-support-plan/other-people-consulted/index.njk
PR to add the basic Yes/No questions and form validation to Other People Consulted page (page 2 in the flow)
Routing and further processing etc will come in subsequent PRs
=> RR-1573 - Add Yes/No question to Other People Consulted page

integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/otherPeopleConsultedListPage.ts, integration_tests/utils/zeroIndexed.ts, server/@types/express/index.d.ts, server/app.ts, server/middleware/requestHelpersMiddleware.ts, server/routes/education-support-plan/create/other-people-consulted/addPersonConsultedController.test.ts, server/routes/education-support-plan/create/other-people-consulted/addPersonConsultedController.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedListController.test.ts, server/routes/education-support-plan/create/other-people-consulted/otherPeopleConsultedListController.ts
PR to implement the "Add another person" button to allow multiple people to be added to the plan
https://github.com/user-attachments/assets/51e7a6e7-a2e5-450e-8ac4-3a719ec7c871
=> RR-1543 - Support for adding multiple people

server/@types/dto/index.d.ts, server/@types/supportAdditionalNeedsApiClient/index.d.ts, server/data/mappers/referenceDataListResponseMapper.test.ts, server/data/mappers/referenceDataListResponseMapper.ts, server/data/supportAdditionalNeedsApiClient.test.ts, server/data/supportAdditionalNeedsApiClient.ts, server/enums/referenceDataDomain.ts, server/services/index.ts, server/services/referenceDataService.test.ts, server/services/referenceDataService.ts, server/testsupport/referenceDataResponseTestDataBuilder.ts
PR to add the API client method, and service class & methods, to get reference data.
Service class methods are for getting:
* conditions
* challenges
* challenge categories
* strengths
* strength categories
At the moment there is no caching - this will be implemented at the service layer in my next PR
=> RR-1690 - Client and Service methods to get reference data

server/@types/viewModels/index.d.ts, server/views/components/actions-card/_strengthsActions.njk, server/views/components/actions-card/actionCardChallenges.test.njk, server/views/components/actions-card/actionCards.test.njk, server/views/components/actions-card/actionsCard.test.ts, server/views/components/actions-card/template.njk, server/views/pages/profile/challenges/index.njk, server/views/pages/profile/strengths/index.njk
Added the action menu for strengths and plumbed it into the Strengths profile page:
=> RR-1684 - Add actions menu to create strength

server/filters/formatStrengthIdentificationSourceFilter.ts, server/routes/strengths/create/detail/detailController.test.ts, server/routes/strengths/create/detail/detailController.ts, server/routes/strengths/create/index.ts, server/utils/nunjucksSetup.ts, server/views/pages/strengths/detail/index.njk, server/views/partials/layout.njk
PR to add the basic controller and nunjucks template for the Detail page of the Create Strength journey:
https://github.com/user-attachments/assets/5a86304f-96c3-4ebd-ab28-e706dbdfb900
=> RR-1684 - Basic controller and nunjucks template for Strength Detail page

server/routes/strengths/create/detail/detailController.test.ts, server/routes/strengths/create/detail/detailController.ts, server/routes/strengths/create/index.ts, server/routes/strengths/validationSchemas/detailSchema.test.ts, server/routes/strengths/validationSchemas/detailSchema.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/strengths/layout.njk
PR that adds the zod validator for the "detail" page in the Create Strengths journey, implements the submit handler for the "detail" page so that it calls the API; and wires everything up to create a full end-to-end journey 👍 
https://github.com/user-attachments/assets/1d98dbbc-cf04-45c1-9390-e9138ea87a37
=> RR-1684 - Zod validator for the "detail" page; submit form & call API

server/routes/additional-learning-needs-screener/create/index.ts, server/routes/additional-learning-needs-screener/create/screener-date/screenerDateController.test.ts, server/routes/additional-learning-needs-screener/create/screener-date/screenerDateController.ts, server/routes/additional-learning-needs-screener/validationSchemas/screenerDateSchema.test.ts, server/routes/additional-learning-needs-screener/validationSchemas/screenerDateSchema.ts, server/views/pages/additional-learning-needs-screener/layout.njk, server/views/pages/additional-learning-needs-screener/screener-date/index.njk
PR that adds the "Screener Date" controller, validator and nunjucks template; all wired up into the journey 👍 
https://github.com/user-attachments/assets/e143f8f1-78be-4a15-8022-c4e685ab8e44
=> RR-1700 - Screener Date controller, validator and view

server/routes/middleware/retrieveReferenceData.test.ts, server/routes/middleware/retrieveReferenceData.ts
Middleware to allow routes to retrieve reference data of a given ref data domain (challenges, strengths, conditions)
This middleware will be wired into a route in my next PR 👍
=> RR-1699 - Middleware to retrieve reference data

integration_tests/e2e/challenges/create/createChallenge.cy.ts, integration_tests/e2e/challenges/create/createChallengePreventOutOfSequenceNavigation.cy.ts, integration_tests/mockApis/supportAdditionalNeedsApi.ts, integration_tests/pages/challenges/addChallengeDetailPage.ts, integration_tests/pages/challenges/selectChallengeCategoryPage.ts, integration_tests/pages/profile/challengesPage.ts, server/routes/challenges/create/detail/detailController.test.ts, server/routes/challenges/create/detail/detailController.ts, server/views/pages/challenges/detail/index.njk
* Add a mirror of the cypress tests added for the strength journey
* Minor update to fix errors not being displayed correctly.
=> RR-1680 Cypress Tests for create challenge journey

server/routes/additional-learning-needs-screener/create/check-your-answers/checkYourAnswersController.test.ts, server/routes/additional-learning-needs-screener/create/check-your-answers/checkYourAnswersController.ts, server/routes/additional-learning-needs-screener/create/index.ts, server/routes/additional-learning-needs-screener/validationSchemas/checkYourAnswersSchema.test.ts, server/routes/additional-learning-needs-screener/validationSchemas/checkYourAnswersSchema.ts, server/views/pages/additional-learning-needs-screener/check-your-answers/index.njk, server/views/partials/layout.njk
PR to add the submit handler for the Check Your Answers page, complete with validation that the user has ticked the checkbox.
At the moment the submit handler does not actually call the API to save the ALN Screener - that will come in my next PR
https://github.com/user-attachments/assets/02353f22-0d5b-42fb-a9b2-1311a225502e
=> RR-1702 - Basic form submit handler and validator

server/views/components/actions-card/_conditionsActions.njk, server/views/components/actions-card/actionsCard.test.ts, server/views/components/actions-card/template.njk, server/views/pages/profile/conditions/index.njk
Added actions menu on the Conditions page:
https://github.com/user-attachments/assets/d54cc2b5-9b11-47db-8998-01065369c8d2
=> RR-1712 - Added actions menu on Conditions page

server/@types/dto/index.d.ts, server/@types/express/index.d.ts, server/data/mappers/createConditionsRequestMapper.test.ts, server/data/mappers/createConditionsRequestMapper.ts, server/routes/challenges/create/middleware/createEmptyChallengeDtoIfNotInJourneyData.test.ts, server/routes/conditions/create/index.ts, server/routes/conditions/create/middleware/checkConditionsListExistsInJourneyData.test.ts, server/routes/conditions/create/middleware/checkConditionsListExistsInJourneyData.ts, server/routes/conditions/create/middleware/createEmptyConditionsListIfNotInJourneyData.test.ts, server/routes/conditions/create/middleware/createEmptyConditionsListIfNotInJourneyData.ts, server/routes/conditions/create/select-conditions/selectConditionsController.test.ts, server/routes/conditions/create/select-conditions/selectConditionsController.ts, server/services/conditionService.test.ts, server/services/conditionService.ts, server/testsupport/conditionDtoTestDataBuilder.ts, server/views/pages/conditions/select-conditions/index.njk
PR for the Add Conditions journey that:
* Updates the DTO (the DTO needs to encapsulate an array of ConditionDto, rather than just being one ConditionDto)
* Updates the mapper
* Creates the middlewares to create the DTO on journeyData, and check the DTO exists on the journeyData
* Wires the middlewares into the routes
* Creates the POST (submit) route
* Wires the validator into the submit route
* Finishes the controller (both the GET and POST methods)
* Unit tests for the controller
* Updates the nunjucks view to check the checkboxes that have been previously selected
https://github.com/user-attachments/assets/ccf787ef-cc36-4ec0-9a40-bf9586b98d4d
=> RR-1703 - Added middlewares and submit handler

server/routes/conditions/create/details/detailsController.ts, server/routes/conditions/create/index.ts, server/views/pages/conditions/details/index.njk
Basic controller and view for the "Conditions details" page
=> RR-1704 - Basic controller and view for the "Conditions details" page

server/data/supportAdditionalNeedsApiClient.test.ts, server/data/supportAdditionalNeedsApiClient.ts
First of smaller PRs for RR-1735
* Updates API client so can call get challenges
=> RR-1735 Update client with get challenges

server/services/challengeService.test.ts, server/services/challengeService.ts
* Update challengeService to add getChallenges method
=> RR-1735 Update challenge service

server/routes/conditions/create/details/detailsController.test.ts, server/routes/conditions/create/details/detailsController.ts, server/routes/conditions/create/index.ts, server/routes/conditions/create/select-conditions/selectConditionsController.test.ts, server/routes/conditions/validationSchemas/detailsSchema.test.ts, server/routes/conditions/validationSchemas/detailsSchema.ts, server/routes/conditions/validationSchemas/selectConditionsSchema.test.ts, server/views/pages/conditions/details/index.njk
PR to add the validator for the Details form of the "Add conditions" journey; add the submit handler in the controller; and wire everything up 👍 
The only bit it doesnt do at the moment is call the API via the service to actually save the  Conditions. That will be my next PR
https://github.com/user-attachments/assets/10570a14-5c16-46eb-9296-12dc2b9f08d4
=> RR-1704 - Validator and submit handler

server/routes/profile/challenges/challengesController.test.ts, server/routes/profile/challenges/challengesController.ts, server/routes/profile/challenges/index.ts, server/routes/profile/index.ts, server/routes/profile/middleware/retrieveCurrentChallenges.test.ts, server/routes/profile/middleware/retrieveCurrentChallenges.ts
* Introduce middleware to retrieve challenges and populate in res locals
* Futher PR to wire into view.
=> RR-1735 Add middleware to retrieve challenges

assets/js/index.js, assets/js/print.mjs, server/views/pages/profile/strengths/components/strengths-summary-card/macro.njk, server/views/pages/profile/strengths/components/strengths-summary-card/strengthsSummaryCard.test.njk, server/views/pages/profile/strengths/components/strengths-summary-card/strengthsSummaryCard.test.ts, server/views/pages/profile/strengths/components/strengths-summary-card/template.njk, server/views/pages/profile/strengths/index.njk
PR to render strengths (both ALN and non-ALN) on the Strengths profile page
https://github.com/user-attachments/assets/b2189ca6-c09f-4d05-9c4c-ad11e8f4841a
=> RR-1741 - Render strengths on Strengths profile page

server/routes/dateComparator.test.ts, server/routes/dateComparator.ts, server/routes/profile/strengths/strengthsController.test.ts, server/routes/profile/strengths/strengthsController.ts
PR that changes the way the Strengths profile page collates the non-ALN and latest ALN strengths ready for rendering on screen.
Previously the route called the middleware to get all strengths, both latest ALN and non-ALN in a single structure; and then the nunjucks template processed this data to group it by strength type, and then within that grouped by non-ALN and ALN strengths (as they need to be rendered differently)
This PR does not change that approach (but will do in a subsequent PR)
Additionally the route calls the middleware to get the prisoner's ALN Screeners, but currently does nothing with that data.
This PR does the grouping within the controller method. Specifically it:
* Gets the **active** non-ALN strengths from the strengths data that the middleware provides …
=> RR-1741 - Group strengths in the controller

server/routes/profile/strengths/index.ts, server/routes/profile/strengths/strengthsController.test.ts, server/routes/profile/strengths/strengthsController.ts, server/views/pages/profile/strengths/components/strengths-summary-card/macro.njk, server/views/pages/profile/strengths/components/strengths-summary-card/strengthsSummaryCard.test.njk, server/views/pages/profile/strengths/components/strengths-summary-card/strengthsSummaryCard.test.ts, server/views/pages/profile/strengths/components/strengths-summary-card/template.njk, server/views/pages/profile/strengths/index.njk, server/views/pages/profile/strengths/index.test.ts
PR to wire in the prison name lookup on the Strengths page
This uses the exact same approach and pattern as was introduced when we did this for Conditions
=> RR-1741 - Prison name lookup on Strengths page

integration_tests/e2e/education-support-plan/create/checkYourAnswersChangeLinks.cy.ts, integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/e2e/education-support-plan/create/createEducationSupportPlanPreventOutOfSequenceNavigation.cy.ts, integration_tests/e2e/education-support-plan/create/removeOtherPeopleConsulted.cy.ts, server/routes/education-support-plan/create/index.ts, server/views/autherror.njk, server/views/components/actions-card/_educationSupportPlanActions.njk, server/views/components/actions-card/_educationSupportPlanActions.test.ts, server/views/pages/profile/overview/index.test.ts
Creation of ELSP is now restricted to only those with the role `ROLE_SAN_EDUCATION_MANAGER`
=> RR-1558 - Apply RBAC to Create ELSP

integration_tests/e2e/education-support-plan/create/checkYourAnswersChangeLinks.cy.ts, integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/checkYourAnswersPage.ts, integration_tests/pages/education-support-plan/learningNeedsSupportPractitionerSupportPage.ts, server/middleware/validationMiddleware.ts, server/routes/education-support-plan/create/learning-needs-support-practitioner-support/learningNeedsSupportPractitionerSupportController.ts, server/routes/education-support-plan/validationSchemas/learningNeedsSupportPractitionerSupportSchema.test.ts, server/routes/education-support-plan/validationSchemas/learningNeedsSupportPractitionerSupportSchema.ts
PR to implement the validator for the new LNSP Support Hours question (is mandatory if the LNSP support is required, and must be a number minimum of 0. No max defined in story)
Because the validation has been implemented in this PR, I have also had to update the cypress tests because there were a couple of tests that went through the Create ELSP journey without completing the Support Hours question, so those tests started to fail due to validation failure 👍  Updated the tests to answer the question / trigger & assert validation etc
https://github.com/user-attachments/assets/7d3661c2-3cd7-423f-9ff0-bd7fbae2ea1c
=> RR-1794 - Validator and cypress tests

assets/scss/components/_profile-overview.scss, assets/scss/index.scss, integration_tests/e2e/profile/overview.cy.ts, integration_tests/pages/profile/overviewPage.ts, server/views/pages/profile/overview/_strengthsSummaryCard.njk, server/views/pages/profile/overview/_strengthsSummaryCard.test.ts, server/views/pages/profile/overview/index.njk, server/views/pages/profile/overview/index.test.ts
=> RR-1757 - Display strengths on Overview page

server/@types/curiousApi/index.d.ts, server/@types/curiousApiClient/index.d.ts, server/data/curiousApiClient.test.ts, server/testsupport/curiousAssessmentsTestDataBuilder.ts
PR to add the Curious API client method (it was actually already there), it's unit tests, the corresponding Curious types (by re-importing their swagger spec), and some test data builders to build instances of their types.
An example of the Curious V2 Assessments response data is as follows. This was built from the test data builders introduced in this PR (with default data), where the understanding of what data could be presented in which fields was taken from [a doc that our BA's have put together](https://justiceuk-my.sharepoint.com/:w:/r/personal/aliki_karnavas_justice_gov_uk/_layouts/15/Doc.aspx?sourcedoc=%7BD7B71FD5-5762-4DD3-A324-D051C76C3DA1%7D&file=New%20S&A%20format.docx=&action=default&mobileredirect=true).
```
{
"v1": [
{
"prn": "A1234BC",
"qualifications": [
{ …
```
=> RR-1753 - Curious API client method and data types to get V2 assessments

assets/scss/components/_profile-overview.scss, server/routes/profile/overview/index.ts, server/routes/profile/overview/overviewController.test.ts, server/routes/profile/overview/overviewController.ts, server/views/pages/profile/overview/_screeningAndAssessmentSummaryCard.njk, server/views/pages/profile/overview/_screeningAndAssessmentSummaryCard.test.ts, server/views/pages/profile/overview/components/ldd-assessments-details/lddAssessmentsDetails.test.njk, server/views/pages/profile/overview/components/ldd-assessments-details/lddAssessmentsDetails.test.ts, server/views/pages/profile/overview/components/ldd-assessments-details/macro.njk, server/views/pages/profile/overview/components/ldd-assessments-details/template.njk, server/views/pages/profile/overview/index.test.ts
PR to render the LDD Assessments in the Screening & Assessments section if there are any:
https://github.com/user-attachments/assets/5f15eb6f-2343-4892-9283-c590801c30cc
=> RR-1753 - Render LDD Assessments

server/@types/dto/index.d.ts, server/data/mappers/educationSupportPlanDtoMapper.test.ts, server/data/mappers/educationSupportPlanDtoMapper.ts, server/data/supportAdditionalNeedsApiClient.test.ts, server/data/supportAdditionalNeedsApiClient.ts, server/routes/profile/middleware/retrieveEducationSupportPlan.test.ts, server/routes/profile/middleware/retrieveEducationSupportPlan.ts, server/services/educationSupportPlanService.test.ts, server/services/educationSupportPlanService.ts, server/testsupport/educationSupportPlanDtoTestDataBuilder.ts
PR that adds the client method, service method and middleware to be able to retrieve the prisoner's Education Support Plan.
Also required a small change to the DTO and it's mapper in order to map the audit fields (createdBy etc)
=> RR-1809 - Client, service and middleware to retrieve Education Support Plan

assets/scss/components/_actions-card.scss, server/views/pages/profile/components/actions-card/actionCards.test.njk, server/views/pages/profile/components/actions-card/actionsCard.test.ts, server/views/pages/profile/components/actions-card/macro.njk, server/views/pages/profile/components/actions-card/template.njk, server/views/pages/profile/education-support-plan/index.njk
PR to add the top section to the Actions Bar showing the plan status
=> RR-1844 - Added top section to Actions Bar showing the plan status

integration_tests/pages/education-support-plan/reviewExistingChallengesPage.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/create/review-existing-needs/reviewExistingChallengesController.test.ts, server/routes/education-support-plan/create/review-existing-needs/reviewExistingChallengesController.ts, server/views/pages/education-support-plan/review-existing-needs/challenges/index.njk, server/views/pages/education-support-plan/review-existing-needs/challenges/index.test.ts
PR to add the Review Challenges page in the Create ELSP journey
(not yet wired into the journey; we will do that when all new pages have been created for the new section of the journey)
=> RR-1791 - Review Challenges page in Create ELSP journey

integration_tests/e2e/education-support-plan/create/checkYourAnswersChangeLinks.cy.ts, integration_tests/e2e/education-support-plan/create/createEducationSupportPlan.cy.ts, integration_tests/e2e/education-support-plan/create/removeOtherPeopleConsulted.cy.ts, integration_tests/pages/education-support-plan/checkYourAnswersPage.ts, integration_tests/pages/education-support-plan/otherPeopleConsultedAddPersonPage.ts, integration_tests/pages/education-support-plan/otherPeopleConsultedListPage.ts, server/routes/education-support-plan/create/other-people-consulted/addPersonConsultedController.test.ts, server/routes/education-support-plan/create/other-people-consulted/addPersonConsultedController.ts, server/routes/education-support-plan/validationSchemas/addPersonConsultedSchema.test.ts, server/routes/education-support-plan/validationSchemas/addPersonConsultedSchema.ts, server/views/pages/education-support-plan/check-your-answers/index.njk, server/views/pages/education-support-plan/other-people-consulted/add-person-consulted/index.njk, server/views/pages/education-support-plan/other-people-consulted/people-consulted-list/index.njk
* Add field for other people consulted job role
* Update validators
* Update several views where job role is to be displayed
* Update cypress tests
=> RR-1790 Add other people consulted job role

assets/scss/overrides/_print.scss
Added new class/style (provided by Westley) to print style sheet
=> RR-1821 - Added new class/style to print style sheet

server/routes/education-support-plan/validationSchemas/learningNeedsSupportPractitionerSupportSchema.test.ts, server/routes/education-support-plan/validationSchemas/learningNeedsSupportPractitionerSupportSchema.ts, server/views/pages/education-support-plan/learning-needs-support-practitioner-support/index.njk
Content change for the LNSP Support Requirements page
=> RR-1917 - Content change for the LNSP Support Requirements page

server/views/pages/education-support-plan/education-health-care-plan/index.njk
* Adds hint text EHCP question
=> RR-1916 Add hint text for EHCP question

server/routes/education-support-plan/validationSchemas/reviewSupportPlanSchema.test.ts, server/views/pages/search/_searchBox.njk, server/views/pages/search/_searchResults.njk, server/views/pages/search/index.njk
PR to update the Search page to include Release Date, whether they have Additional Needs, and whether they are In Education
Also some minor content changes
=> RR-1745 - Add new columns & content changes to Search page

integration_tests/e2e/education-support-plan/review/reviewEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/whoReviewedThePlanPage.ts, server/@types/dto/index.d.ts, server/data/mappers/educationSupportPlanDtoMapper.test.ts, server/data/mappers/educationSupportPlanDtoMapper.ts, server/enums/planReviewedByValue.ts, server/routes/education-support-plan/review/index.ts, server/routes/education-support-plan/review/middleware/retrieveEducationSupportPlan.test.ts, server/routes/education-support-plan/review/middleware/retrieveEducationSupportPlan.ts, server/routes/education-support-plan/review/who-reviewed-the-plan/whoReviewedThePlanController.test.ts, server/routes/education-support-plan/review/who-reviewed-the-plan/whoReviewedThePlanController.ts, server/routes/education-support-plan/validationSchemas/whoReviewedThePlanSchema.test.ts, server/routes/education-support-plan/validationSchemas/whoReviewedThePlanSchema.ts, server/services/educationSupportPlanService.test.ts, server/testsupport/educationSupportPlanDtoTestDataBuilder.ts, server/views/pages/education-support-plan/layout.njk, server/views/pages/education-support-plan/who-reviewed-the-plan/index.njk
PR to implement the 'Who reviewed the plan' page of the Review ELSP journey, including:
* Changes to the DTO to add new properties for the new questions on this page
* Changes to middleware to only retrieve the ELSP if it has not already been retrieved
* Implement the new controller
* Implement the new validator
* Implement the new view
* Cypress tests (which will be fleshed out as we implement each page in the Review journey)
=> RR-1776 - 'Who reviewed the plan' page of the Review ELSP journey

integration_tests/e2e/education-support-plan/review/reviewEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/individualViewOnProgressPage.ts, server/@types/dto/index.d.ts, server/routes/education-support-plan/review/index.ts, server/routes/education-support-plan/review/individual-view-on-progress/individualViewOnProgressController.test.ts, server/routes/education-support-plan/review/individual-view-on-progress/individualViewOnProgressController.ts, server/routes/education-support-plan/review/other-people-consulted/otherPeopleConsultedController.test.ts, server/routes/education-support-plan/review/other-people-consulted/otherPeopleConsultedController.ts, server/routes/education-support-plan/review/other-people-consulted/otherPeopleConsultedListController.test.ts, server/routes/education-support-plan/review/other-people-consulted/otherPeopleConsultedListController.ts, server/routes/education-support-plan/validationSchemas/individualViewOnProgressSchema.test.ts, server/routes/education-support-plan/validationSchemas/individualViewOnProgressSchema.ts, server/testsupport/reviewEducationSupportPlanDtoTestDataBuilder.ts, server/views/pages/education-support-plan/individual-view-on-progress/index.njk
PR to add the 'Prisoner view on progress' page of the Review ELSP journey
https://github.com/user-attachments/assets/7214d6a3-00aa-474c-89bf-22010c8d098f
=> RR-1779 - 'Prisoner view on progress' page of the Review ELSP journey

integration_tests/e2e/education-support-plan/review/reviewEducationSupportPlan.cy.ts, integration_tests/pages/education-support-plan/teachingAdjustmentsPage.ts, server/routes/education-support-plan/create/index.ts, server/routes/education-support-plan/review/index.ts, server/routes/education-support-plan/review/teaching-adjustments/teachingAdjustmentsController.test.ts, server/routes/education-support-plan/review/teaching-adjustments/teachingAdjustmentsController.ts, server/routes/education-support-plan/validationSchemas/teachingAdjustmentsSchema.test.ts, server/routes/education-support-plan/validationSchemas/teachingAdjustmentsSchema.ts, server/views/pages/education-support-plan/teaching-adjustments/index.njk, server/views/partials/layout.njk
PR to add the 'Teaching adjustment' page to the Review ELSP journey
https://github.com/user-attachments/assets/884034db-3db6-4180-bf49-0761fb937a1f
=> RR-1779 - 'Teaching adjustment' page of the Review ELSP journey
